"""One-off authoring pass that adds the second wave of Chapter 1 gear to Docs/items.json."""
import json
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "Docs"


def item(item_id, kind, rarity, value, name_en, name_id, desc_en, desc_id, **extra):
    entry = {
        "id": item_id, "kind": kind, "rarity": rarity, "value": value,
        "name": {"en": name_en, "id": name_id},
        "desc": {"en": desc_en, "id": desc_id},
    }
    entry.update(extra)
    return entry


NEW_ITEMS = [
    item("sword_hearth", "Weapon", "Fine", 190, "Hearthsteel Blade", "Bilah Baja Perapian",
         "Quenched in oathfire instead of water. The edge holds a little warmth, and the dead flinch from it.",
         "Dipadamkan dalam api sumpah, bukan air. Matanya menyimpan sedikit hangat, dan orang mati menghindarinya.",
         slot="MainHand", damage=19, attackSpeed=1.0),
    item("sword_warden_oath", "Weapon", "Rare", 520, "Warden's Oath", "Sumpah Warden",
         "Crane's own sword, left in the cellar with the point driven into the floor. He never came back for it.",
         "Pedang milik Crane sendiri, ditinggalkan di ruang bawah dengan ujung tertancap di lantai. Ia tak pernah kembali mengambilnya.",
         slot="MainHand", damage=27, attackSpeed=1.05, health=10),
    item("axe_grave", "Weapon", "Fine", 165, "Gravecutter", "Pembelah Kubur",
         "Meant for roots, not bone. It stopped caring about the difference two winters ago.",
         "Dibuat untuk akar, bukan tulang. Dua musim dingin lalu ia berhenti peduli bedanya.",
         slot="MainHand", damage=22, attackSpeed=0.8),
    item("axe_harrow", "Weapon", "Rare", 460, "Greymarch Warcleaver", "Pembelah Perang Greymarch",
         "Ducal issue. Heavy enough that the Duke's men swing it with both hands and their whole grudge.",
         "Perlengkapan kadipaten. Cukup berat sampai anak buah Adipati mengayunkannya dengan dua tangan dan seluruh dendamnya.",
         slot="MainHand", damage=31, attackSpeed=0.7, moveSpeed=-0.04),
    item("spear_ash", "Weapon", "Fine", 210, "Ashwood Pike", "Tombak Kayu Abu",
         "Long enough to keep a burning thing at arm's length, which is all anyone asks of a pike.",
         "Cukup panjang untuk menahan sesuatu yang terbakar tetap sejauh lengan, dan hanya itu yang diminta dari sebuah tombak.",
         slot="MainHand", damage=18, attackSpeed=1.15),
    item("bow_hunter", "Weapon", "Fine", 230, "Longbow of the Vale", "Busur Panjang Lembah",
         "Drawn properly it puts a shaft through a skull at eighty paces. Drawn badly it breaks your thumb.",
         "Ditarik benar, ia menembus tengkorak dari delapan puluh langkah. Ditarik salah, ibu jarimu patah.",
         slot="MainHand", damage=16, attackSpeed=1.3),
    item("bow_black", "Weapon", "Rare", 495, "Blackfletch", "Bulu Hitam",
         "Tobias made it from a yew that grew out of a mass grave. He will tell you that story only once.",
         "Tobias membuatnya dari pohon yew yang tumbuh dari kuburan massal. Cerita itu hanya akan ia ceritakan sekali.",
         slot="MainHand", damage=23, attackSpeed=1.35, moveSpeed=0.03),
    item("staff_apothecary", "Weapon", "Fine", 240, "Apothecary's Staff", "Tongkat Tabib",
         "Hollow, stoppered, and full of things that should not share a shelf. Iskra insists it is perfectly safe.",
         "Berongga, bersumbat, dan penuh benda yang seharusnya tak disimpan berdekatan. Iskra bersikeras itu aman.",
         slot="MainHand", damage=14, attackSpeed=1.1, health=15),
    item("dagger_quiet", "Weapon", "Fine", 140, "Quiet Work", "Kerja Sunyi",
         "A merchant's knife, balanced for throwing and for deniability.",
         "Pisau pedagang, seimbang untuk dilempar sekaligus untuk disangkal.",
         slot="OffHand", damage=9, attackSpeed=1.5),

    item("armor_refugee", "Armor", "Common", 48, "Patched Wool", "Wol Bertambal",
         "Someone's winter coat, cut down twice and handed on twice more.",
         "Mantel musim dingin milik seseorang, dipotong dua kali dan diwariskan dua kali lagi.",
         slot="Body", armor=5, health=14),
    item("armor_warden_coat", "Armor", "Fine", 240, "Warden's Long Coat", "Mantel Panjang Warden",
         "Waxed against rain and grave-damp, with deep pockets for what wardens are not supposed to carry.",
         "Dilapisi lilin penahan hujan dan lembap kubur, dengan saku dalam untuk benda yang seharusnya tak dibawa warden.",
         slot="Body", armor=11, health=26),
    item("armor_ash_harness", "Armor", "Rare", 540, "Ash Marshal Harness", "Harnes Marsekal Abu",
         "Issued to the crews who walk into burning villages. It smells of smoke and will not stop.",
         "Perlengkapan regu yang masuk ke desa terbakar. Baunya asap, dan tak pernah hilang.",
         slot="Body", armor=17, health=30, moveSpeed=-0.05),
    item("armor_bone_lattice", "Armor", "Oathbound", 900, "Bone Lattice", "Jalinan Tulang",
         "Iskra's work: splints of femur bound in grave wax. The dead hesitate before striking their own.",
         "Buatan Iskra: bilah tulang paha yang diikat lilin kubur. Orang mati ragu memukul sesama mereka sendiri.",
         slot="Body", armor=20, health=40, moveSpeed=-0.02),
    item("helm_warden", "Armor", "Fine", 175, "Warden's Wide Hat", "Topi Lebar Warden",
         "Keeps rain off the neck and lets everyone see your face. Brann says the second part matters more.",
         "Menahan hujan dari tengkuk dan membuat wajahmu terlihat. Kata Brann, bagian kedua lebih penting.",
         slot="Head", armor=6, health=8),
    item("helm_marshal", "Armor", "Rare", 380, "Soot Hood", "Tudung Jelaga",
         "Filtered cloth and smoked glass. You can breathe in a burning street, and be told apart from the people in it.",
         "Kain penyaring dan kaca berasap. Kau bisa bernapas di jalan yang terbakar, dan bisa dibedakan dari orang-orang di dalamnya.",
         slot="Head", armor=11),
    item("shield_warden", "Armor", "Fine", 210, "Hearth Round", "Perisai Bundar Perapian",
         "The hearth mark is painted, not forged. It still makes refugees stand a little straighter.",
         "Lambang perapiannya dicat, bukan ditempa. Tetap saja membuat para pengungsi berdiri lebih tegak.",
         slot="OffHand", armor=9, health=10, moveSpeed=-0.02),
    item("shield_tower", "Armor", "Rare", 430, "Vigil Tower Shield", "Perisai Menara Jaga",
         "Big enough to sleep behind, which is exactly what the night watch does with it.",
         "Cukup besar untuk tidur di baliknya, dan memang begitulah penjaga malam memakainya.",
         slot="OffHand", armor=15, health=18, moveSpeed=-0.07),

    item("trinket_tally", "Trinket", "Common", 70, "Gravedigger's Tally", "Hitungan Penggali Kubur",
         "A notched stick. Sixty years of names, and Brann can still recite any notch you point at.",
         "Sebilah kayu bertakik. Enam puluh tahun nama, dan Brann masih bisa menyebut takik mana pun yang kau tunjuk.",
         slot="Trinket", health=12),
    item("trinket_salt_seal", "Trinket", "Fine", 220, "Salt League Seal", "Segel Serikat Garam",
         "Opens gates, closes mouths, and costs more than either.",
         "Membuka gerbang, menutup mulut, dan harganya lebih mahal dari keduanya.",
         slot="Trinket", damage=2, moveSpeed=0.05),
    item("trinket_lion_pin", "Trinket", "Fine", 260, "Scaled Lion Pin", "Pin Singa Bersisik",
         "Wearing the Protector's crest in Rennfall is either loyalty or bait. Nobody has decided which.",
         "Memakai lambang Protektor di Rennfall bisa berarti kesetiaan atau umpan. Belum ada yang memutuskan.",
         slot="Trinket", armor=5, health=15),
    item("trinket_ember_knot", "Trinket", "Rare", 430, "Ember Knot", "Simpul Bara",
         "A cord soaked in hearth ash, tied with a knot nobody living remembers how to undo.",
         "Tali yang direndam abu perapian, diikat dengan simpul yang tak seorang pun ingat cara membukanya.",
         slot="Trinket", damage=6, health=18),
    item("trinket_crane_seal", "Trinket", "Oathbound", 0, "Crane's Warden Seal", "Segel Warden Crane",
         "The old warden's seal of office. The wax under it is forty years old and still soft.",
         "Segel jabatan warden lama. Lilin di bawahnya berusia empat puluh tahun dan masih lunak.",
         slot="Trinket", damage=8, health=25, setsFlag="relic.crane_seal"),

    item("potion_stoneskin", "Consumable", "Rare", 95, "Stoneskin Draught", "Ramuan Kulit Batu",
         "Tastes of wet slate. For an hour, a blade feels like a shove.",
         "Rasanya seperti batu tulis basah. Selama sejam, tebasan hanya terasa seperti dorongan.",
         stackSize=6, healAmount=25),
    item("potion_nightsight", "Consumable", "Fine", 48, "Nightsight Tincture", "Tetes Mata Malam",
         "The dark goes grey and the cold goes sharp. Do not use it twice in one night.",
         "Gelap berubah kelabu dan dingin terasa menusuk. Jangan pakai dua kali dalam semalam.",
         stackSize=8, manaAmount=35),
    item("food_stew", "Consumable", "Common", 14, "Hearth Stew", "Sup Perapian",
         "Root vegetables, salt pork, and whatever the traps caught. Eaten standing, always.",
         "Umbi, daging asin, dan apa pun hasil jerat. Selalu dimakan sambil berdiri.",
         stackSize=10, healAmount=45),
    item("bandage", "Consumable", "Common", 12, "Boiled Linen", "Kain Linen Rebus",
         "Boiled, dried, rolled. The only medicine in the valley that never runs out.",
         "Direbus, dikeringkan, digulung. Satu-satunya obat di lembah yang tak pernah habis.",
         stackSize=15, healAmount=28),
    item("oil_flask", "Consumable", "Fine", 40, "Pitch Flask", "Botol Ter",
         "Throw it, light it, and do not stand downwind of your own idea.",
         "Lempar, sulut, dan jangan berdiri searah angin dari idemu sendiri.",
         stackSize=8),
    item("whetstone", "Consumable", "Common", 18, "Whetstone", "Batu Asah",
         "Ten minutes of work for an hour of not dying. Fair trade.",
         "Sepuluh menit kerja untuk sejam tidak mati. Pertukaran yang adil.",
         stackSize=10),

    item("mat_rope", "Material", "Common", 9, "Tarred Rope", "Tali Ter",
         "Holds roofs down, holds prisoners still, holds a bridge together for one more crossing.",
         "Menahan atap, mengikat tawanan, dan menyatukan jembatan untuk satu penyeberangan lagi.",
         stackSize=99),
    item("mat_nails", "Material", "Common", 11, "Iron Nails", "Paku Besi",
         "Hand-forged, uneven, and worth more than the plank they hold.",
         "Ditempa tangan, tidak seragam, dan lebih berharga daripada papan yang dipakukan.",
         stackSize=99),
    item("mat_pitch", "Material", "Fine", 22, "Pine Pitch", "Getah Pinus",
         "Waterproofs a roof, seals a wound badly, and burns like a promise.",
         "Menahan bocor di atap, menutup luka dengan buruk, dan terbakar seperti sebuah janji.",
         stackSize=60),
    item("mat_hide", "Material", "Common", 16, "Cured Hide", "Kulit Samak",
         "Deer, mostly. The valley's deer have been nervous for forty years.",
         "Kebanyakan dari rusa. Rusa di lembah ini sudah gelisah selama empat puluh tahun.",
         stackSize=60),
    item("mat_saltbrick", "Material", "Fine", 30, "Salt Brick", "Bata Garam",
         "League currency in all but name. Preserves meat, pays bribes, melts in rain.",
         "Mata uang Serikat dalam segala hal kecuali namanya. Mengawetkan daging, membayar suap, larut kena hujan.",
         stackSize=40),
    item("tool_shovel", "Trinket", "Common", 55, "Iron Shovel", "Sekop Besi",
         "Brann's spare. Carrying it marks you as someone who intends to bury people properly.",
         "Cadangan milik Brann. Membawanya menandakan kau berniat mengubur orang dengan layak.",
         slot="Trinket", damage=3, health=6),
    item("tool_lantern", "Trinket", "Fine", 120, "Warden's Lantern", "Lentera Warden",
         "Shuttered on three sides. You see the road; the road does not see you.",
         "Tertutup di tiga sisi. Kau melihat jalan, dan jalan tidak melihatmu.",
         slot="Trinket", moveSpeed=0.04, health=8),

    item("quest_burn_ledger", "Quest", "Rare", 0, "Burning Crew Ledger", "Buku Catatan Regu Pembakar",
         "Every village cleared, with a column for souls accounted. The last column is always full and always wrong.",
         "Setiap desa yang dibersihkan, dengan kolom jiwa tercatat. Kolom terakhir selalu penuh dan selalu salah.",
         setsFlag="quest.burn_ledger"),
    item("quest_moot_writ", "Quest", "Oathbound", 0, "Writ of the Moot", "Surat Sidang Mahkota",
         "Signed, sealed, and worth a war. Holding it makes you the most invited and most hunted person in Valcaris.",
         "Ditandatangani, disegel, dan bernilai satu perang. Memegangnya membuatmu orang paling diundang sekaligus paling diburu di Valcaris.",
         setsFlag="quest.moot_writ"),
    item("relic_root_crown_shard", "Relic", "Oathbound", 0, "Shard of the Root Crown", "Serpihan Mahkota Akar",
         "A splinter of the crown that broke over the queen. It is still growing, very slowly, in the dark of your pack.",
         "Serpihan mahkota yang retak di kepala Ratu. Ia masih tumbuh, sangat perlahan, di dalam gelap tasmu.",
         slot="Trinket", damage=10, health=30, setsFlag="relic.crown_shard"),
]


def main() -> None:
    path = DOCS / "items.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = {entry["id"] for entry in data["items"]}
    added = [entry for entry in NEW_ITEMS if entry["id"] not in existing]
    data["items"].extend(added)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"added {len(added)} items; total {len(data['items'])}")


if __name__ == "__main__":
    main()
